class Configuration:
    CAPTURE_WIDTH = 3840
    CAPTURE_HEIGHT = 2160
    CAPTURE_FPS = 30
    CAPTURE_ROTATION = 0  # Possible values: 0, 90, 180, 270
    CAPTURE_FLIP_HORIZONTAL = True
    CAPTURE_FLIP_VERTICAL = False
    CAMERA_INDEX = 0
    CAPTURE_FREQUENCY = 1
    CHECKPOINT_FREQUENCY = 5
    BATCH_FREQUENCY = 5
    BUFFER_SIZE = 150
    IS_MOCK = False
    CONTRACT_ADDRESS = "<YOUR_CONTRACT_ADDRESS>"
    STORAGE_URL = "<YOUR_PROJECT_ID>.appspot.com"
